function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of plot x data
%  Y1:  vector of plot y data

%  Auto-generated by MATLAB on 01-May-2026 14:26:22

% Create figure
figure1 = figure('Name','Figure','Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1);

% Create ylabel
ylabel('Flux (LMH)');

% Create xlabel
xlabel('Time (min)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 1000]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 50]);
box(axes1,'on');
hold(axes1,'off');
% Create textarrow
annotation(figure1,'textarrow',[0.658333333333333 0.592261904761904],...
    [0.746619047619048 0.642857142857143],'String',{'Flux peaks'});

% Create textarrow
annotation(figure1,'textarrow',[0.375 0.413392857142856],...
    [0.25 0.322222222222223],'String',{'Fouling','intensifies'});

% Create textarrow
annotation(figure1,'textarrow',[0.739583333333333 0.648511904761904],...
    [0.373809523809524 0.216666666666668],...
    'String',{'Flux plateaus','(sometimes)'});

% Create textarrow
annotation(figure1,'textarrow',[0.808928571428571 0.746428571428571],...
    [0.232730158730159 0.140873015873016],'String',{'Flux','stops'});

